source "https://rubygems.org"

gem "jekyll"
gem "jekyll_ext"
gem "liquid"
gem "rdiscount"
gem "nokogiri"
gem "jekyll-speakerdeck", github: "flyerhzm/jekyll-speakerdeck"
gem "jekyll-tagging"
gem "capistrano"
gem "capistrano-bundler"
gem "capistrano-rvm"
